package it.hibernate;
// Generated 22-feb-2019 8.27.08 by Hibernate Tools 5.0.6.Final

import java.util.Date;

/**
 * DeptEmp generated by hbm2java
 */
public class DeptEmpOutput implements java.io.Serializable {
	private SimpleDepartment department;
	private SimpleEmployee employees;
	private Date fromDate;
	private Date toDate;

	public DeptEmpOutput() {
	}

	public DeptEmpOutput(SimpleEmployee employees, SimpleDepartment department, Date fromDate, Date toDate) {
		this.employees = employees;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.setDepartment(department);
	}
	public SimpleEmployee getEmployees() {
		return this.employees;
	}

	public void setEmployees(SimpleEmployee employees) {
		this.employees = employees;
	}
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public SimpleDepartment getDepartment() {
		return department;
	}

	public void setDepartment(SimpleDepartment department) {
		this.department = department;
	}
}