package it.hibernate;
// Generated 22-feb-2019 8.27.08 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeptManager generated by hbm2java
 */
public class DeptManOutput implements java.io.Serializable {
	private SimpleDepartment department;
	private SimpleEmployee employees;
	private Date fromDate;
	private Date toDate;

	public DeptManOutput() {
	}

	public DeptManOutput(SimpleEmployee employees, SimpleDepartment department, Date fromDate, Date toDate) {
		this.employees = employees;
		this.setDepartment(department);
		this.fromDate = fromDate;
		this.toDate = toDate;
	}
	public SimpleEmployee getEmployees() {
		return this.employees;
	}

	public void setEmployees(SimpleEmployee employees) {
		this.employees = employees;
	}
	
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}
	
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public SimpleDepartment getDepartment() {
		return department;
	}

	public void setDepartment(SimpleDepartment department) {
		this.department = department;
	}

}
